(()=>{
  'use strict';
  const M=VisualModel,$=s=>document.querySelector(s),state=M.seed();let month='2026-09',selected='2026-09-28',serial=100;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const yen=n=>'¥'+n.toLocaleString('ja-JP'),kinds={day:'日勤',night:'夜勤',contract:'請負'},company=id=>state.companies.find(c=>c.id===id);
  function render(){
    $('#month-title').textContent=Number(month.slice(0,4))+'年'+Number(month.slice(5))+'月';
    $('#prev').disabled=month==='2000-01';$('#next').disabled=month==='2100-12';
    $('#weeks').innerHTML=M.weeks(month,state.entries).map(w=>'<div class="week"><div class="dates">'+w.days.map((d,i)=>'<button class="date '+(d.slice(0,7)!==month?'outside ':'')+(i===5?'sat ':i===6?'sun ':'')+(d==='2026-09-28'?'today':'')+'" data-date="'+d+'" aria-label="'+d+' の予定"><span>'+Number(d.slice(8))+'</span></button>').join('')+'</div><div class="events" style="grid-template-rows:repeat('+w.lanes+',var(--unused,auto))">'+w.segments.map(s=>{const e=s.entry,c=company(e.company),full=c.name+' ／ '+e.site+'（'+kinds[e.kind]+'）';return '<button class="event '+e.kind+(s.continuesBefore?' before':'')+(s.continuesAfter?' after':'')+'" style="grid-column:'+(s.left+1)+' / '+(s.right+2)+';grid-row:'+(s.lane+1)+'" data-entry="'+esc(e.id)+'" aria-label="'+esc(full)+'" title="'+esc(full)+'">'+esc(c.short)+' / '+esc(e.site)+'</button>';}).join('')+'</div></div>').join('');
    const t=M.totals(month,state.entries);$('#total-qty').innerHTML=esc(t.qty)+'<small>人工</small>';$('#total-sales').textContent=yen(t.sales);
  }
  function showDay(d){selected=d;$('#day-title').textContent=Number(d.slice(5,7))+'月'+Number(d.slice(8))+'日の予定';const list=state.entries.filter(e=>e.start<=d&&e.end>=d);$('#day-entries').innerHTML=list.length?list.map(e=>'<article class="record"><div class="record-top"><span class="badge '+e.kind+'">'+kinds[e.kind]+'</span><button data-edit="'+esc(e.id)+'">編集</button></div><h3>'+esc(e.site)+'</h3><p>'+esc(company(e.company).name)+'</p><p>'+esc(e.qty)+'人工 ・ '+yen(e.rate)+' / 日</p>'+(e.start!==e.end?'<p>'+esc(e.start)+' 〜 '+esc(e.end)+'</p>':'')+(e.notes?'<p>'+esc(e.notes)+'</p>':'')+'</article>').join(''):'<p class="hint">この日の予定はありません。</p>';$('#day-dialog').showModal();}
  function openEntry(id){const e=state.entries.find(e=>e.id===id)||{id:'',start:selected,end:selected,company:state.companies[0].id,site:'',kind:'day',qty:1,rate:state.companies[0].rate,notes:''},f=$('#entry-form');f.reset();f.elements.company.innerHTML=state.companies.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('');for(const key of ['id','start','end','company','site','kind','qty','rate','notes'])f.elements[key].value=e[key];$('#entry-title').textContent=e.id?'予定を編集':'予定を追加';$('#delete').hidden=!e.id;$('#entry-error').textContent='';f.querySelector('details').open=!!e.notes;$('#entry-dialog').showModal();}
  function showCompanies(){ $('#company-list').innerHTML=state.companies.map(c=>'<article class="record"><h3>'+esc(c.name)+'</h3><p>'+esc(c.short)+' ／ '+esc(c.formal)+'</p><p>日勤 '+yen(c.rate)+' ・ 夜勤 '+yen(c.nightRate)+'</p></article>').join(''); }
  document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.look){document.body.dataset.look=b.dataset.look;document.querySelectorAll('.switch button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const refined=b.dataset.look==='refined';$('#look-title').textContent=refined?'見慣れた配置を、そのまま美しく。':'現在の雰囲気と、見比べる。';$('#look-description').textContent=refined?'文字の強弱と余白を整え、予定の色はやさしく。大切な情報が自然に目に入るバランスに。':'青いヘッダー、太めの文字、鮮やかな予定の帯。比較用に現在の雰囲気を再現しています。';}if(b.dataset.date)showDay(b.dataset.date);if(b.dataset.entry){const e=state.entries.find(e=>e.id===b.dataset.entry);selected=e.start;openEntry(e.id);}if(b.dataset.edit){$('#day-dialog').close();openEntry(b.dataset.edit);}});
  for(const [id,n] of [['prev',-1],['next',1]])$('#'+id).onclick=()=>{const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);month=d.toISOString().slice(0,7);selected=month+'-01';render();};
  $('#sample-month').onclick=()=>{month='2026-09';selected='2026-09-28';render();};$('#add').onclick=()=>openEntry();$('#day-add').onclick=()=>{$('#day-dialog').close();openEntry();};$('#companies').onclick=()=>{showCompanies();$('#company-dialog').showModal();};
  $('#entry-form').elements.start.onchange=ev=>{const f=$('#entry-form');if(f.elements.end.value<ev.target.value)f.elements.end.value=ev.target.value;};
  for(const key of ['company','kind'])$('#entry-form').elements[key].onchange=()=>{const f=$('#entry-form'),c=company(f.elements.company.value),kind=f.elements.kind.value;f.elements.rate.value=kind==='night'?c.nightRate:c.rate;if(kind==='contract')f.elements.qty.value=0;else if(Number(f.elements.qty.value)===0)f.elements.qty.value=1;};
  $('#entry-form').onsubmit=ev=>{ev.preventDefault();const f=ev.currentTarget,e=Object.fromEntries(new FormData(f));e.qty=Number(e.qty);e.rate=Number(e.rate);if(!M.validEntry(e,state.companies)){$('#entry-error').textContent='日付の順序・人工・単価を確認してください。期間は367日以内です。';return;}e.site=e.site.trim();e.id=e.id||'e'+serial++;const at=state.entries.findIndex(x=>x.id===e.id);if(at<0)state.entries.push(e);else state.entries[at]=e;month=e.start.slice(0,7);selected=e.start;render();$('#entry-dialog').close();};
  $('#delete').onclick=()=>{const id=$('#entry-form').elements.id.value;state.entries=state.entries.filter(e=>e.id!==id);render();$('#entry-dialog').close();};
  $('#company-form').onsubmit=ev=>{ev.preventDefault();const f=ev.currentTarget,c=Object.fromEntries(new FormData(f));for(const key of ['name','short','formal']){c[key]=c[key].trim();if(!c[key]){f.elements[key].setCustomValidity('会社名を入力してください。');f.elements[key].reportValidity();return;}}c.rate=Number(c.rate);c.nightRate=Number(c.nightRate);if(![c.rate,c.nightRate].every(n=>Number.isFinite(n)&&n>=0&&n<=10000000))return;c.id='c'+serial++;state.companies.push(c);showCompanies();f.reset();$('#company-message').textContent='「'+c.name+'」を見本に追加しました。予定入力で選べます。';};
  $('#company-form').addEventListener('input',ev=>ev.target.setCustomValidity?.(''));
  render();
})();
